---
title: "Using Vector Embeddings For Sentiment Analysis"
author: "Rod Acosta, Kevin Furbish, Ibrahim Khan, Anthony Washington"
format: 
  revealjs:
    theme: moon
    
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib
always_allow_html: true
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

# Introduction {.smaller .scrollable}

- What is NLP?
  - Natural Language Processing (NLP) is a field of artificial intelligence that focuses on the interaction between computers and human language. It involves teaching computers to understand, interpret, and respond to human language in a useful way.

---

## Sentiment Analysis {.smaller .scrollable}

- Sentiment Analysis is a technique used in NLP to determine the emotional tone behind words. It helps to understand the sentiment expressed in text, whether it is positive, negative, or neutral.

::: {.panel-tabset}

### Importance of Sentiment Analysis

- Essential for understanding public opinion, aiding businesses in refining marketing strategies, improving products, and enhancing customer satisfaction.
- The rise of social media and e-commerce platforms has increased the importance of sentiment analysis for real-time consumer behavior insights.

### Case Study: Twitter Data

- Hasan, Maliha, and Arifuzzaman (2019) used Twitter data to demonstrate the potential of sentiment analysis.
- Their methodology combined Bag of Words (BoW) and Term Frequency-Inverse Document Frequency (TF-IDF) models with logistic regression, achieving an accuracy of 85.25% in classifying tweets as positive or negative [@9036670].

:::

## Sentiment Analysis (Continued) {.smaller}

::: {.panel-tabset}

### Case Study: E-commerce Reviews

- Kathuria, Sethi, and Negi (2022) applied sentiment analysis to e-commerce reviews using various machine learning models (logistic regression, AdaBoost, SVM, Naive Bayes, and random forest).
- Analyzed the Women’s E-commerce Clothing Reviews dataset to understand consumer behavior and the impact of electronic word-of-mouth (eWOM) on customer attitudes and product sales [@10093674].

### Case Study: Granular Approach

- Nasukawa and Yi (2003) focused on extracting sentiments linked to specific subjects rather than entire documents.
- Their prototype system used a syntactic parser and sentiment lexicon to detect sentiments in web pages and news articles, offering detailed insights into specific opinions [@nasukawa2003sentiment].

:::

---

- Conclusion:
  - These studies illustrate the evolution and application of sentiment analysis using NLP, highlighting its critical role in extracting insights from vast amounts of text data for strategic decision-making.
  
---

## Vector Embeddings In Natural Language Processing {.smaller}

- Vector Embeddings are a way to represent words or phrases in numerical form. Each word or phrase is converted into a vector (a list of numbers) which captures its meaning based on the context it is used in.
- Vector embeddings transform text data into a numerical format that can be used by machine learning models. This numerical representation captures the semantic meaning of words and phrases.

- Advantages of Embeddings:
  - <b>Contextual Understanding:</b> Captures the meaning of words based on their context.
  - <b>Semantic Similarity:</b> Words with similar meanings have similar vector representations.
  - <b>Dimensionality Reduction:</b> Reduces complex text data into simpler numerical form.

---

- Advanced Embedding Models:
  - Sentence embeddings build on word embeddings to represent sentences, improving over Bag of Words models, which have high dimensionality and sparseness issues[@pilehvar2020embeddings].
  - Document embeddings further extend this concept to encode entire documents for NLP tasks where word ordering is important[@pilehvar2020embeddings].

---

## Using Embeddings For Sentiment Analysis {.smaller}

- Performance Improvement:
  - Word embedding and deep learning models have significantly enhanced NLP tasks, including sentiment analysis [@10255396].
  - Popular methods include Word2Vec and Global Vectors (GloVe), trained on different datasets (Google News and Wikipedia 2014, respectively) [@10543279].

- Challenges with Pre-trained Embeddings:
  - Pre-trained word embeddings often fail to capture contextual sentiment information, leading to inaccuracies (e.g., mapping "good" and "bad" to neighboring vectors) [@9397340][@7296633].
  - The paper aims to explore these challenges and investigate alternative embedding methods for more accurate sentiment analysis.

---
